### ISSUE TITLE
Search Bar based on Tags in field Tasg of Metadata

### ISSUE THREAD

**Issue by dosteinacher** [adobe/inside-aem#66]
We will add more tags into the metadata based on the PLG posts. Main tags will be this ones:
- just do it
- immersion
- high frequency, low stakes
- iterate
- serve using software
- immediate disintermediation
- open meritocracy
- your users, your teammates
- everyone does projects
- trade risk for velocity
- closed loop
- value pipeline
- dare to be wrong, take pride in being humble
- happy, live, and fast
- code settles arguments

I want to have a bar above the blogs where one can select one or more tags to get the right blog posts. 
Additionally, the search should give results based on what search is fining in the metadata Tags.

**Comment by mtilburgadobe** [comment]
will be "fixed" by #20
